- hosts: sonar
  become: true
  tasks:
  - name: "Installing wget"
    package:
      name:
      - wget
      - zip
      state: present
  
  - name: "Create group sonar"
    group:
      name: sonar
      state: present
  
  - name: "Create user sonar"
    user:
      name: sonar
      group: sonar

  - name: "Installation of java"
    package:
      name: openjdk-11-jdk
      state: present

  - name: "Installation of postgres"
    shell: "wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | apt-key add -"

  - shell: "echo deb http://apt.postgresql.org/pub/repos/apt/ lsb_release -cs-pgdg main >> /etc/apt/sources.list.d/pgdg.list"

  - package:
      name:
      - postgresql
      - postgresql-contrib
      state: present

  - service:
      name: postgresql
      state: started
      enabled: yes
    
  - name: "Installation of sonarqube"
    shell: "wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.5.0.56709.zip"
  
  - unarchive:
      src: sonarqube-9.5.0.56709.zip
      dest: .
      remote_src: yes
  
  - file:
      path: /opt/sonarqube
      state: absent

  - shell: "mv sonarqube-9.5.0.56709 /opt/sonarqube"

  - name: "Chown to sonar user"
    file:
      path: /opt/sonarqube
      state: directory
      owner: sonar
      group: sonar
      recurse: yes

  - name: "Apply Page Template"
    template:
      src: templates/sonarqube.service.j2
      dest: /etc/systemd/system/sonarqube.service

  - service:
      name: sonarqube
      state: started
      enabled: yes