- hosts: jenkins
  become: true
  tasks:
  - name: "Installing curl"
    apt:
      pkg:
      - curl
      - zip
      - wget
      update_cache: yes
      state: present

  - name: "Installation of java"
    package:
      name: openjdk-11-jdk
      state: present

  - name: "Getting jenkins key"
    shell: "curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null"
  
  - name: "Echo jenkins repo"
    shell: 'echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null'
  
  - name: "Installation of jenkins"
    package:
      name: jenkins
      state: present

  # - name: "Removing previous downloads"
  #   shell: "rm sonar-scanner-cli-4.7.0.2747-linux.zip && rm -rf sonar-scanner-cli-4.7.0.2747-linux"
    
  - name: "Downloading of sonar-scanner"
    shell: "wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip"

  - name: "Unpackage sonar-scanner"
    unarchive:
      src: sonar-scanner-cli-4.7.0.2747-linux.zip
      dest: .
      remote_src: yes

  - file:
      path: /opt/sonar-scanner
      state: absent

  - shell: "mv sonar-scanner-4.7.0.2747-linux /opt/sonar-scanner"

  - shell: "echo 'export PATH=$PATH:/opt/sonar-scanner/bin' | tee -a /etc/profile"
