- hosts: kubernetes
  become: true
  tasks:
  - name: "Installing curl"
    package:
      name: 
      - curl
      - ca-certificates
      - gnupg
      - lsb-release
      state: present
  
  - name: Creates directory
    file:
      path: /etc/apt/keyrings
      state: directory
  
  - shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg"
  
  - name: "Echo repo docker" 
    shell: 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'

  - name: "Download docker"
    package:
      name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-compose-plugin
      state: present
      
  - name: "Installation of kind"
    shell: "curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.14.0/kind-linux-amd64 && chmod +x ./kind && sudo mv ./kind /usr/local/bin/kind"

  - name: "Create kind cluster"
    shell: "kind create cluster --name kind"