Vagrant.configure('2') do |config|
    config.vm.box = 'ubuntu/bionic64'
    config.vm.hostname = 'jenkins'
    config.vm.network :forwarded_port, guest: 8080, host: 8080
    config.vm.network :private_network, ip: '10.0.0.2'

    $script = <<-SCRIPT
    sudo chmod 700 /vagrant
    SCRIPT
 
    config.vm.provision "shell", inline: $script
    # config.vm.provision :file, source: '~/.ssh/id_rsa.pub', destination: '~/.ssh/authorized_keys'
end