Vagrant.configure("2") do |config|
  config.vm.box = 'ubuntu/bionic64'
  config.vm.network :private_network, ip: '10.0.0.1'
  config.vm.provision :shell, path: 'provision.sh'

  $script = <<-SCRIPT
    sudo chmod 700 /vagrant
    SCRIPT
 
  config.vm.provision "shell", inline: $script
end